<?php
/**
 * Plugin Name:       Shihela Contextual Site Assistant PRO
 * Plugin URI:        https://yukdigitalz.com/shihela-contextual-site-assistant
 * Description:       PRO Extension for Shihela Contextual Site Assistant. Adds advanced multi-agent support, chat logs, custom knowledge bases, and proactive triggers.
 * Version:           1.0.0
 * Author:            Shihela
 * Author URI:        https://yukdigitalz.com/
 * License:           GPL-2.0+
 * Text Domain:       shihela-contextual-site-assistant-pro
 * Domain Path:       /languages
 */

// Block direct access
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Main PRO Plugin class.
 */
class Shihela_Contextual_Site_Assistant_Pro {

	/**
	 * Constructor.
	 */
	public function __construct() {
		// Verify if the FREE version is active
		add_action( 'plugins_loaded', array( $this, 'check_free_version_dependency' ) );
	}

	/**
	 * Check if the core/free version of the plugin is active.
	 * If not, show an admin notice and auto-deactivate this PRO version.
	 */
	public function check_free_version_dependency() {
		// Check for the presence of the core/free version class
		if ( ! class_exists( 'Shihela_Contextual_Site_Assistant' ) ) {
			add_action( 'admin_notices', array( $this, 'render_dependency_error_notice' ) );

			// Deactivate this PRO plugin safely
			deactivate_plugins( plugin_basename( __FILE__ ) );
			if ( isset( $_GET['activate'] ) ) {
				unset( $_GET['activate'] );
			}
			return;
		}

		// Initialize PRO features if core is active
		$this->init_pro_features();
	}

	/**
	 * Render warning notice in the Admin panel when Core Free version is missing.
	 */
	public function render_dependency_error_notice() {
		?>
		<div class="error notice is-dismissible">
			<p>
				<strong><?php esc_html_e( 'Shihela Contextual Site Assistant PRO', 'shihela-contextual-site-assistant-pro' ); ?></strong> 
				<?php esc_html_e( 'requires the free version (Shihela Contextual Site Assistant) to be installed and active. The PRO extension has been deactivated.', 'shihela-contextual-site-assistant-pro' ); ?>
			</p>
		</div>
		<?php
	}

	/**
	 * Initialize all PRO version logic and hook into the FREE version actions/filters.
	 */
	private function init_pro_features() {
		// Example Hook 1: Hook into the FREE version's settings to add a PRO-only section
		add_action( 'admin_init', array( $this, 'register_pro_settings' ) );

		// Example Hook 2: Capture chat logs when a message response is received (Fase 1)
		add_action( 'shihela_chat_response_received', array( $this, 'log_chat_transaction' ), 10, 3 );
	}

	/**
	 * Register settings specific to the PRO version.
	 */
	public function register_pro_settings() {
		// Add PRO licensing fields or advanced configuration here
	}

	/**
	 * Log the session chat details to the custom PRO DB tables.
	 *
	 * @param string $response   The response generated by the AI model.
	 * @param string $message    The original user message.
	 * @param string $session_id The visitor's session token.
	 */
	public function log_chat_transaction( $response, $message, $session_id ) {
		// Code to write chat logs to wp_shihela_chat_messages table goes here (Fase 1)
	}
}

// Instantiate the PRO plugin
new Shihela_Contextual_Site_Assistant_Pro();
